# -*- coding: utf-8 -*-
"""Assignment3_25b4538.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fNkmKXGLbvMe_CHCjSnTmI0u_mQEiOx
"""

import pandas as pd
import cvxpy as cp
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
from math import sqrt

TICKERS = ["RELIANCE.NS", "TCS.NS", "HDFCBANK.NS"] #you can choose assets of your own wish

df = yf.download(TICKERS, period="3y")
prices = df.xs("Close", axis=1, level=0)

prices = prices.fillna(method="ffill").dropna()
prices.head()

log_returns_hdfc = np.log(prices['HDFCBANK.NS']/prices['HDFCBANK.NS'].shift(1))
log_returns_tcs = np.log(prices['TCS.NS']/prices['TCS.NS'].shift(1))
log_returns_reliance = np.log(prices['RELIANCE.NS']/prices['RELIANCE.NS'].shift(1))
log_returns = pd.DataFrame([log_returns_hdfc,log_returns_reliance,log_returns_tcs])
log_returns = log_returns.T
log_returns=log_returns.dropna()        #TO DO : calculate log return
log_returns.head()

sqrt=np.sqrt
TRADING_DAYS = 252
mu = log_returns.mean()*TRADING_DAYS                      #TO DO : Calculate Expected return (annual)
cov_matrix = log_returns.std()*sqrt(TRADING_DAYS)              #TO DO : Calculate Covariance matrix

# mu, cov_matrix

df=pd.DataFrame()
df['mu']=mu
df['cov_matrix']=cov_matrix
mu.shape, cov_matrix.shape

from cvxpy.problems.objective import Maximize
mu = np.array(mu).reshape(3,1)
Sigma = log_returns.cov().values
w= cp.Variable((3, 1))
R= float(input('Enter minimum expected logreturn: '))
 #expected logreturn
constraints = [cp.sum(w) == 1, w>=0, mu.T@w>=R]
objective = cp.Minimize(cp.quad_form(w, Sigma))
problem = cp.Problem(objective, constraints)
problem.solve()
print('The portfolio that gives the return R at the minimum possible risk is:\n',w.value.T)
var = (w.value.T)@(Sigma)@(w.value)
print('The stdev of this portfolio is: ',var)
print('The Expected return of this portfolio is: ', mu.T@w.value)